### ISSUE TITLE
ReferenceError: window is not defined when using server side render

### ISSUE THREAD

**Issue by InstanceOfMichael** [lokyoung/vuejs-paginate#32]
```
Nuxt.js Error:

ReferenceError: window is not defined
    at /project/node_modules/vuejs-paginate/dist/index.js:1:3284
    at /home/project/node_modules/vuejs-paginate/dist/index.js:1:3216
    at e.exports (/home/project/node_modules/vuejs-paginate/dist/index.js:1:3502)
    at Object.<anonymous> (/home/project/node_modules/vuejs-paginate/dist/index.js:1:705)
    at t (/home/project/node_modules/vuejs-paginate/dist/index.js:1:336)
    at Object.<anonymous> (/home/project/node_modules/vuejs-paginate/dist/index.js:1:565)
    at t (/home/project/node_modules/vuejs-paginate/dist/index.js:1:336)
    at Object.<anonymous> (/home/project/node_modules/vuejs-paginate/dist/index.js:1:516)
    at t (/home/project/node_modules/vuejs-paginate/dist/index.js:1:336)
    at e.__esModule.default (/home/project/node_modules/vuejs-paginate/dist/index.js:1:423)
    at /home/project/node_modules/vuejs-paginate/dist/index.js:1:428
    at n (/home/project/node_modules/vuejs-paginate/dist/index.js:1:81)
    at Object.<anonymous> (/home/project/node_modules/vuejs-paginate/dist/index.js:1:207)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/project/node_modules/babel-register/lib/node.js:152:7)
```

**Comment by InstanceOfMichael** [comment]
This works:

```
import Paginate from 'vuejs-paginate/src/components/Paginate';
const todoService = app.service('api/v1/todos');

export default {
  components: {
    removeButton,
    Paginate,
  },
```

**Comment by lokyoung** [comment]
Hello @InstanceOfMichael . Hope this component works well in your project. Any issue just contact me. Thanks.

**Comment by sbefort** [comment]
While this works, it is an ugly hack.  The problem is that the module references the `window` and `document` objects, which do not exist on the server side (only available in the browser).  For example, this function is a problem when run on the server side:

`function(){return/msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase())}`

Why do the files in the src directory **NOT** reference the `window` and `document` objects, but the files in the `dist` directory do?

**Comment by heshamelmasry77** [comment]
okay so what is the solution for this because i am still getting it nothing changed
